// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIlmB5TgGb2g3qcfbYtdUi5MqIzgGlCF8',
    appId: '1:660990465343:web:2022182b06d1d03ce3af8a',
    messagingSenderId: '660990465343',
    projectId: 'safesignal-71957',
    authDomain: 'safesignal-71957.firebaseapp.com',
    storageBucket: 'safesignal-71957.appspot.com',
    measurementId: 'G-8LBCHB9DYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXZGPMlfWMxx17S-f0S5fpPYM4xoij5xY',
    appId: '1:660990465343:android:15ddb36d2a4fda0de3af8a',
    messagingSenderId: '660990465343',
    projectId: 'safesignal-71957',
    storageBucket: 'safesignal-71957.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0iastjq7swrHvVQ8HJBTt4A1tKGzCJlY',
    appId: '1:660990465343:ios:051dbbb9d3246737e3af8a',
    messagingSenderId: '660990465343',
    projectId: 'safesignal-71957',
    storageBucket: 'safesignal-71957.appspot.com',
    androidClientId: '660990465343-kimnbrssim3s4hgol4iagh9p13akosah.apps.googleusercontent.com',
    iosClientId: '660990465343-lnanoic0142jh26g19iskb91hmn7ae7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0iastjq7swrHvVQ8HJBTt4A1tKGzCJlY',
    appId: '1:660990465343:ios:051dbbb9d3246737e3af8a',
    messagingSenderId: '660990465343',
    projectId: 'safesignal-71957',
    storageBucket: 'safesignal-71957.appspot.com',
    androidClientId: '660990465343-kimnbrssim3s4hgol4iagh9p13akosah.apps.googleusercontent.com',
    iosClientId: '660990465343-lnanoic0142jh26g19iskb91hmn7ae7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIlmB5TgGb2g3qcfbYtdUi5MqIzgGlCF8',
    appId: '1:660990465343:web:22a3e829db5ac6c6e3af8a',
    messagingSenderId: '660990465343',
    projectId: 'safesignal-71957',
    authDomain: 'safesignal-71957.firebaseapp.com',
    storageBucket: 'safesignal-71957.appspot.com',
    measurementId: 'G-XMSVSM53Z0',
  );
}
